version: '3'
services:
  app:
    build:
      args:
        user: app
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    image: app
    restart: unless-stopped
    working_dir: /home/app/
    volumes:
      - ./:/home/app/
    environment:
      - DEBUG=test123
    ports:
      - 3000:3000
      